export interface Document {
  id: string;
  title: string;
  category: string;
  filename: string;
}

export const documentCatalog: Document[] = [
  { id: "ABM", title: "ABM", category: "Marketing", filename: "ARG-Builder-ABM.md" },
  { id: "ACV-Optimization", title: "ACV Optimization", category: "Revenue & Pricing", filename: "ARG-Builder-ACV-Optimization.md" },
  { id: "AI-ML-Governance", title: "AI ML Governance", category: "AI & Developer", filename: "ARG-Builder-AI-ML-Governance.md" },
  { id: "AI-ML-Strategy", title: "AI ML Strategy", category: "AI & Developer", filename: "ARG-Builder-AI-ML-Strategy.md" },
  { id: "API-Design-Developer-Portal", title: "API Design Developer Portal", category: "Engineering", filename: "ARG-Builder-API-Design-Developer-Portal.md" },
  { id: "API-Developer-Platform", title: "API Developer Platform", category: "Engineering", filename: "ARG-Builder-API-Developer-Platform.md" },
  { id: "API-Documentation-Developer-Portal", title: "API Documentation Developer Portal", category: "Engineering", filename: "ARG-Builder-API-Documentation-Developer-Portal.md" },
  { id: "API-Gateway-Service-Mesh", title: "API Gateway Service Mesh", category: "Engineering", filename: "ARG-Builder-API-Gateway-Service-Mesh.md" },
  { id: "API-Monetization", title: "API Monetization", category: "Engineering", filename: "ARG-Builder-API-Monetization.md" },
  { id: "API-Rate-Limiting-Throttling", title: "API Rate Limiting Throttling", category: "Engineering", filename: "ARG-Builder-API-Rate-Limiting-Throttling.md" },
  { id: "API-Versioning-Deprecation", title: "API Versioning Deprecation", category: "Engineering", filename: "ARG-Builder-API-Versioning-Deprecation.md" },
  { id: "API-Versioning-and-Deprecation-Lifecycle-Management", title: "API Versioning and Deprecation Lifecycle Management", category: "Engineering", filename: "ARG-Builder-API-Versioning-and-Deprecation-Lifecycle-Management.md" },
  { id: "Accessibility-Testing-WCAG", title: "Accessibility Testing WCAG", category: "Product", filename: "ARG-Builder-Accessibility-Testing-WCAG.md" },
  { id: "Account-Based-Experience-ABX-Strategy", title: "Account Based Experience ABX Strategy", category: "Marketing", filename: "ARG-Builder-Account-Based-Experience-ABX-Strategy.md" },
  { id: "Account-Based-Marketing", title: "Account Based Marketing", category: "Marketing", filename: "ARG-Builder-Account-Based-Marketing.md" },
  { id: "Account-Mapping-Org-Intelligence", title: "Account Mapping Org Intelligence", category: "Strategy & Operations", filename: "ARG-Builder-Account-Mapping-Org-Intelligence.md" },
  { id: "Accounting-Financial-Close", title: "Accounting Financial Close", category: "Finance & Legal", filename: "ARG-Builder-Accounting-Financial-Close.md" },
  { id: "Admin-Panel-Back-Office", title: "Admin Panel Back Office", category: "Strategy & Operations", filename: "ARG-Builder-Admin-Panel-Back-Office.md" },
  { id: "Advisor-Network-Board", title: "Advisor Network Board", category: "Strategy & Operations", filename: "ARG-Builder-Advisor-Network-Board.md" },
  { id: "Advisory-Board", title: "Advisory Board", category: "Strategy & Operations", filename: "ARG-Builder-Advisory-Board.md" },
  { id: "Affiliate-Marketing-Program", title: "Affiliate Marketing Program", category: "Marketing", filename: "ARG-Builder-Affiliate-Marketing-Program.md" },
  { id: "Analytics-Event-Taxonomy", title: "Analytics Event Taxonomy", category: "Marketing", filename: "ARG-Builder-Analytics-Event-Taxonomy.md" },
  { id: "Annual-Planning", title: "Annual Planning", category: "Strategy & Operations", filename: "ARG-Builder-Annual-Planning.md" },
  { id: "Architecture-Decision-Records", title: "Architecture Decision Records", category: "Engineering", filename: "ARG-Builder-Architecture-Decision-Records.md" },
  { id: "Async-Communication-Culture", title: "Async Communication Culture", category: "Strategy & Operations", filename: "ARG-Builder-Async-Communication-Culture.md" },
  { id: "Audit-Logging-Compliance", title: "Audit Logging Compliance", category: "Security & Compliance", filename: "ARG-Builder-Audit-Logging-Compliance.md" },
  { id: "Automated-Deployment-Rollback", title: "Automated Deployment Rollback", category: "Engineering", filename: "ARG-Builder-Automated-Deployment-Rollback.md" },
  { id: "Automated-Testing-Pyramid", title: "Automated Testing Pyramid", category: "Engineering", filename: "ARG-Builder-Automated-Testing-Pyramid.md" },
  { id: "B2B-Influencer-Marketing-Playbook", title: "B2B Influencer Marketing Playbook", category: "Marketing", filename: "ARG-Builder-B2B-Influencer-Marketing-Playbook.md" },
  { id: "Background-Job-Queue-Architecture", title: "Background Job Queue Architecture", category: "Engineering", filename: "ARG-Builder-Background-Job-Queue-Architecture.md" },
  { id: "Banking-Financial-Infrastructure", title: "Banking Financial Infrastructure", category: "Engineering", filename: "ARG-Builder-Banking-Financial-Infrastructure.md" },
  { id: "Billing-Infrastructure-Subscription", title: "Billing Infrastructure Subscription", category: "Finance & Legal", filename: "ARG-Builder-Billing-Infrastructure-Subscription.md" },
  { id: "Board-Deck-Reporting", title: "Board Deck Reporting", category: "Strategy & Operations", filename: "ARG-Builder-Board-Deck-Reporting.md" },
  { id: "Board-Deck-Template", title: "Board Deck Template", category: "Strategy & Operations", filename: "ARG-Builder-Board-Deck-Template.md" },
  { id: "Board-Governance", title: "Board Governance", category: "Strategy & Operations", filename: "ARG-Builder-Board-Governance.md" },
  { id: "Board-Meeting-Prep", title: "Board Meeting Prep", category: "Strategy & Operations", filename: "ARG-Builder-Board-Meeting-Prep.md" },
  { id: "Board-Observer-Information-Rights", title: "Board Observer Information Rights", category: "Strategy & Operations", filename: "ARG-Builder-Board-Observer-Information-Rights.md" },
  { id: "Brand-Identity", title: "Brand Identity", category: "Marketing", filename: "ARG-Builder-Brand-Identity.md" },
  { id: "Brand-Voice-Messaging", title: "Brand Voice Messaging", category: "Marketing", filename: "ARG-Builder-Brand-Voice-Messaging.md" },
  { id: "Business-Continuity-DR", title: "Business Continuity DR", category: "Operations", filename: "ARG-Builder-Business-Continuity-DR.md" },
  { id: "Business-Plan", title: "Business Plan", category: "Strategy & Operations", filename: "ARG-Builder-Business-Plan.md" },
  { id: "CAB-Framework", title: "CAB Framework", category: "Strategy & Operations", filename: "ARG-Builder-CAB-Framework.md" },
  { id: "CDN-Strategy", title: "CDN Strategy", category: "Engineering", filename: "ARG-Builder-CDN-Strategy.md" },
  { id: "CDP-Architecture", title: "CDP Architecture", category: "Engineering", filename: "ARG-Builder-CDP-Architecture.md" },
  { id: "CICD-Pipeline-Design", title: "CICD Pipeline Design", category: "Engineering", filename: "ARG-Builder-CICD-Pipeline-Design.md" },
  { id: "CS-Automation-Tech-Touch", title: "CS Automation Tech Touch", category: "Strategy & Operations", filename: "ARG-Builder-CS-Automation-Tech-Touch.md" },
  { id: "CS-Metrics-Dashboard", title: "CS Metrics Dashboard", category: "Strategy & Operations", filename: "ARG-Builder-CS-Metrics-Dashboard.md" },
  { id: "CS-Metrics-OKRs", title: "CS Metrics OKRs", category: "Strategy & Operations", filename: "ARG-Builder-CS-Metrics-OKRs.md" },
  { id: "CS-QBR-Framework", title: "CS QBR Framework", category: "Customer Success", filename: "ARG-Builder-CS-QBR-Framework.md" },
  { id: "Caching-Strategy-Architecture", title: "Caching Strategy Architecture", category: "Engineering", filename: "ARG-Builder-Caching-Strategy-Architecture.md" },
  { id: "Cap-Table-Dilution-Modeling", title: "Cap Table Dilution Modeling", category: "Finance & Legal", filename: "ARG-Builder-Cap-Table-Dilution-Modeling.md" },
  { id: "Case-Study-Production-Pipeline", title: "Case Study Production Pipeline", category: "Engineering", filename: "ARG-Builder-Case-Study-Production-Pipeline.md" },
  { id: "Cash-Management-Treasury", title: "Cash Management Treasury", category: "Finance & Legal", filename: "ARG-Builder-Cash-Management-Treasury.md" },
  { id: "Champion-Development-Internal-Selling", title: "Champion Development Internal Selling", category: "Customer Success", filename: "ARG-Builder-Champion-Development-Internal-Selling.md" },
  { id: "Changelog-Release-Communication", title: "Changelog Release Communication", category: "Engineering", filename: "ARG-Builder-Changelog-Release-Communication.md" },
  { id: "Channel-Enablement", title: "Channel Enablement", category: "Partnerships & GTM", filename: "ARG-Builder-Channel-Enablement.md" },
  { id: "Channel-Partner-Enablement", title: "Channel Partner Enablement", category: "Partnerships & GTM", filename: "ARG-Builder-Channel-Partner-Enablement.md" },
  { id: "Churn-Analysis-Exit-Interview", title: "Churn Analysis Exit Interview", category: "Customer Success", filename: "ARG-Builder-Churn-Analysis-Exit-Interview.md" },
  { id: "Churn-Prevention", title: "Churn Prevention", category: "Customer Success", filename: "ARG-Builder-Churn-Prevention.md" },
  { id: "Cloud-FinOps", title: "Cloud FinOps", category: "Engineering", filename: "ARG-Builder-Cloud-FinOps.md" },
  { id: "Code-Quality-Static-Analysis", title: "Code Quality Static Analysis", category: "Engineering", filename: "ARG-Builder-Code-Quality-Static-Analysis.md" },
  { id: "Code-Review-Culture", title: "Code Review Culture", category: "Engineering", filename: "ARG-Builder-Code-Review-Culture.md" },
  { id: "Cohort-Analysis-Playbook", title: "Cohort Analysis Playbook", category: "Data & Analytics", filename: "ARG-Builder-Cohort-Analysis-Playbook.md" },
  { id: "Community-Led-Growth", title: "Community Led Growth", category: "Strategy & Operations", filename: "ARG-Builder-Community-Led-Growth.md" },
  { id: "Community-Platform", title: "Community Platform", category: "Strategy & Operations", filename: "ARG-Builder-Community-Platform.md" },
  { id: "Company-Wiki", title: "Company Wiki", category: "Strategy & Operations", filename: "ARG-Builder-Company-Wiki.md" },
  { id: "Competitive-Battle-Cards", title: "Competitive Battle Cards", category: "Sales", filename: "ARG-Builder-Competitive-Battle-Cards.md" },
  { id: "Competitive-Displacement", title: "Competitive Displacement", category: "Sales", filename: "ARG-Builder-Competitive-Displacement.md" },
  { id: "Competitive-Intelligence", title: "Competitive Intelligence", category: "Sales", filename: "ARG-Builder-Competitive-Intelligence.md" },
  { id: "Competitive-Moat", title: "Competitive Moat", category: "Sales", filename: "ARG-Builder-Competitive-Moat.md" },
  { id: "Competitive-Positioning", title: "Competitive Positioning", category: "Sales", filename: "ARG-Builder-Competitive-Positioning.md" },
  { id: "Competitive-Response", title: "Competitive Response", category: "Sales", filename: "ARG-Builder-Competitive-Response.md" },
  { id: "Compliance-Audit", title: "Compliance Audit", category: "Security & Compliance", filename: "ARG-Builder-Compliance-Audit.md" },
  { id: "Compliance-Automation-GRC", title: "Compliance Automation GRC", category: "Security & Compliance", filename: "ARG-Builder-Compliance-Automation-GRC.md" },
  { id: "Compliance-Automation", title: "Compliance Automation", category: "Security & Compliance", filename: "ARG-Builder-Compliance-Automation.md" },
  { id: "Compliance-Privacy", title: "Compliance Privacy", category: "Security & Compliance", filename: "ARG-Builder-Compliance-Privacy.md" },
  { id: "Containerization-Kubernetes", title: "Containerization Kubernetes", category: "Engineering", filename: "ARG-Builder-Containerization-Kubernetes.md" },
  { id: "Content-Calendar", title: "Content Calendar", category: "Marketing", filename: "ARG-Builder-Content-Calendar.md" },
  { id: "Content-Distribution-Syndication", title: "Content Distribution Syndication", category: "Marketing", filename: "ARG-Builder-Content-Distribution-Syndication.md" },
  { id: "Content-Marketing-Playbook", title: "Content Marketing Playbook", category: "Marketing", filename: "ARG-Builder-Content-Marketing-Playbook.md" },
  { id: "Content-Repurposing", title: "Content Repurposing", category: "Marketing", filename: "ARG-Builder-Content-Repurposing.md" },
  { id: "Continuous-Deployment-Progressive-Delivery", title: "Continuous Deployment Progressive Delivery", category: "Engineering", filename: "ARG-Builder-Continuous-Deployment-Progressive-Delivery.md" },
  { id: "Contract-Lifecycle-Management", title: "Contract Lifecycle Management", category: "Customer Success", filename: "ARG-Builder-Contract-Lifecycle-Management.md" },
  { id: "Contract-Negotiation", title: "Contract Negotiation", category: "Sales", filename: "ARG-Builder-Contract-Negotiation.md" },
  { id: "Crisis-Communication", title: "Crisis Communication", category: "Strategy & Operations", filename: "ARG-Builder-Crisis-Communication.md" },
  { id: "Crisis-Communications", title: "Crisis Communications", category: "Strategy & Operations", filename: "ARG-Builder-Crisis-Communications.md" },
  { id: "Cross-Functional-Operating-Cadence", title: "Cross Functional Operating Cadence", category: "Strategy & Operations", filename: "ARG-Builder-Cross-Functional-Operating-Cadence.md" },
  { id: "Culture-Scaling-Playbook", title: "Culture Scaling Playbook", category: "Strategy & Operations", filename: "ARG-Builder-Culture-Scaling-Playbook.md" },
  { id: "Culture-Values", title: "Culture Values", category: "Strategy & Operations", filename: "ARG-Builder-Culture-Values.md" },
  { id: "Customer-Advisory-Board", title: "Customer Advisory Board", category: "Strategy & Operations", filename: "ARG-Builder-Customer-Advisory-Board.md" },
  { id: "Customer-Advocacy-Champion", title: "Customer Advocacy Champion", category: "Customer Success", filename: "ARG-Builder-Customer-Advocacy-Champion.md" },
  { id: "Customer-Advocacy", title: "Customer Advocacy", category: "Customer Success", filename: "ARG-Builder-Customer-Advocacy.md" },
  { id: "Customer-Community", title: "Customer Community", category: "Customer Success", filename: "ARG-Builder-Customer-Community.md" },
  { id: "Customer-Data-Platform", title: "Customer Data Platform", category: "Customer Success", filename: "ARG-Builder-Customer-Data-Platform.md" },
  { id: "Customer-Digital-Experience-Score-DXS-Framework-An-Operational-Guide-for-ARG-Builder", title: "Customer Digital Experience Score DXS Framework An Operational Guide for ARG Builder", category: "Customer Success", filename: "ARG-Builder-Customer-Digital-Experience-Score-DXS-Framework-An-Operational-Guide-for-ARG-Builder.md" },
  { id: "Customer-Digital-Twin-and-Predictive-Modeling", title: "Customer Digital Twin and Predictive Modeling", category: "Customer Success", filename: "ARG-Builder-Customer-Digital-Twin-and-Predictive-Modeling.md" },
  { id: "Customer-Discovery-Guide", title: "Customer Discovery Guide", category: "Customer Success", filename: "ARG-Builder-Customer-Discovery-Guide.md" },
  { id: "Customer-Education", title: "Customer Education", category: "Customer Success", filename: "ARG-Builder-Customer-Education.md" },
  { id: "Customer-Escalation-Management", title: "Customer Escalation Management", category: "Customer Success", filename: "ARG-Builder-Customer-Escalation-Management.md" },
  { id: "Customer-Expansion-Playbook", title: "Customer Expansion Playbook", category: "Customer Success", filename: "ARG-Builder-Customer-Expansion-Playbook.md" },
  { id: "Customer-Feedback-Loop", title: "Customer Feedback Loop", category: "Customer Success", filename: "ARG-Builder-Customer-Feedback-Loop.md" },
  { id: "Customer-Health-Score-Engineering", title: "Customer Health Score Engineering", category: "Customer Success", filename: "ARG-Builder-Customer-Health-Score-Engineering.md" },
  { id: "Customer-Health-Score", title: "Customer Health Score", category: "Customer Success", filename: "ARG-Builder-Customer-Health-Score.md" },
  { id: "Customer-Health-Scoring", title: "Customer Health Scoring", category: "Customer Success", filename: "ARG-Builder-Customer-Health-Scoring.md" },
  { id: "Customer-Journey-Orchestration", title: "Customer Journey Orchestration", category: "Customer Success", filename: "ARG-Builder-Customer-Journey-Orchestration.md" },
  { id: "Customer-Journey", title: "Customer Journey", category: "Customer Success", filename: "ARG-Builder-Customer-Journey.md" },
  { id: "Customer-Lifecycle-Revenue-Optimization-Framework-for-ARG-Builder", title: "Customer Lifecycle Revenue Optimization Framework for ARG Builder", category: "Customer Success", filename: "ARG-Builder-Customer-Lifecycle-Revenue-Optimization-Framework-for-ARG-Builder.md" },
  { id: "Customer-Migration-Data-Import", title: "Customer Migration Data Import", category: "Customer Success", filename: "ARG-Builder-Customer-Migration-Data-Import.md" },
  { id: "Customer-Migration-and-Data-Import-Strategy", title: "Customer Migration and Data Import Strategy", category: "Customer Success", filename: "ARG-Builder-Customer-Migration-and-Data-Import-Strategy.md" },
  { id: "Customer-Migration", title: "Customer Migration", category: "Customer Success", filename: "ARG-Builder-Customer-Migration.md" },
  { id: "Customer-Multi-Touch-Attribution-and-Journey-Analytics", title: "Customer Multi Touch Attribution and Journey Analytics", category: "Marketing", filename: "ARG-Builder-Customer-Multi-Touch-Attribution-and-Journey-Analytics.md" },
  { id: "Customer-Onboarding", title: "Customer Onboarding", category: "Customer Success", filename: "ARG-Builder-Customer-Onboarding.md" },
  { id: "Customer-Outcome-Based-Pricing-and-Value-Metrics", title: "Customer Outcome Based Pricing and Value Metrics", category: "Revenue & Pricing", filename: "ARG-Builder-Customer-Outcome-Based-Pricing-and-Value-Metrics.md" },
  { id: "Customer-Outcome-Based-Success-Framework", title: "Customer Outcome Based Success Framework", category: "Customer Success", filename: "ARG-Builder-Customer-Outcome-Based-Success-Framework.md" },
  { id: "Customer-Predictive-Revenue-Analytics-and-Expansion-Scoring", title: "Customer Predictive Revenue Analytics and Expansion Scoring", category: "Customer Success", filename: "ARG-Builder-Customer-Predictive-Revenue-Analytics-and-Expansion-Scoring.md" },
  { id: "Customer-Proactive-Churn-Intervention-and-Save-Desk-Operations", title: "Customer Proactive Churn Intervention and Save Desk Operations", category: "Customer Success", filename: "ARG-Builder-Customer-Proactive-Churn-Intervention-and-Save-Desk-Operations.md" },
  { id: "Customer-Reference-Program", title: "Customer Reference Program", category: "Customer Success", filename: "ARG-Builder-Customer-Reference-Program.md" },
  { id: "Customer-Renewal-Playbook", title: "Customer Renewal Playbook", category: "Customer Success", filename: "ARG-Builder-Customer-Renewal-Playbook.md" },
  { id: "Customer-Revenue-Retention-Waterfall-Analysis-and-Reporting", title: "Customer Revenue Retention Waterfall Analysis and Reporting", category: "Customer Success", filename: "ARG-Builder-Customer-Revenue-Retention-Waterfall-Analysis-and-Reporting.md" },
  { id: "Customer-Segmentation", title: "Customer Segmentation", category: "Customer Success", filename: "ARG-Builder-Customer-Segmentation.md" },
  { id: "Customer-Sentiment-Analysis-Voice-of-Customer-Intelligence", title: "Customer Sentiment Analysis Voice of Customer Intelligence", category: "Customer Success", filename: "ARG-Builder-Customer-Sentiment-Analysis-Voice-of-Customer-Intelligence.md" },
  { id: "Customer-Success-Operations-at-Driving-Scalable-Growth-through-Data-", title: "Customer Success Operations at Driving Scalable Growth through Data ", category: "Customer Success", filename: "ARG-Builder-Customer-Success-Operations-at-ARG-Builder-Driving-Scalable-Growth-through-Data-.md" },
  { id: "Customer-Success", title: "Customer Success", category: "Customer Success", filename: "ARG-Builder-Customer-Success.md" },
  { id: "Customer-Value-Realization-Framework-and-Time-to-Value-Optimization", title: "Customer Value Realization Framework and Time to Value Optimization", category: "Customer Success", filename: "ARG-Builder-Customer-Value-Realization-Framework-and-Time-to-Value-Optimization.md" },
  { id: "Customer-Win-Back", title: "Customer Win Back", category: "Customer Success", filename: "ARG-Builder-Customer-Win-Back.md" },
  { id: "Customer-Zero-Party-Data-Collection-SaaS-Vertical-AI-Agent-Strategy", title: "Customer Zero Party Data Collection SaaS Vertical AI Agent Strategy", category: "AI & Developer", filename: "ARG-Builder-Customer-Zero-Party-Data-Collection-SaaS-Vertical-AI-Agent-Strategy.md" },
  { id: "DEI-Program", title: "DEI Program", category: "Strategy & Operations", filename: "ARG-Builder-DEI-Program.md" },
  { id: "Dark-Mode-Theming-Architecture", title: "Dark Mode Theming Architecture", category: "Product", filename: "ARG-Builder-Dark-Mode-Theming-Architecture.md" },
  { id: "Data-Analytics", title: "Data Analytics", category: "Data & Analytics", filename: "ARG-Builder-Data-Analytics.md" },
  { id: "Data-Driven-Decisions", title: "Data Driven Decisions", category: "Strategy & Operations", filename: "ARG-Builder-Data-Driven-Decisions.md" },
  { id: "Data-Enrichment-Segmentation", title: "Data Enrichment Segmentation", category: "Data & Analytics", filename: "ARG-Builder-Data-Enrichment-Segmentation.md" },
  { id: "Data-Export-Portability", title: "Data Export Portability", category: "Strategy & Operations", filename: "ARG-Builder-Data-Export-Portability.md" },
  { id: "Data-Export-Reporting-API", title: "Data Export Reporting API", category: "Engineering", filename: "ARG-Builder-Data-Export-Reporting-API.md" },
  { id: "Data-Governance", title: "Data Governance", category: "Strategy & Operations", filename: "ARG-Builder-Data-Governance.md" },
  { id: "Data-Import-CSV-Upload", title: "Data Import CSV Upload", category: "Strategy & Operations", filename: "ARG-Builder-Data-Import-CSV-Upload.md" },
  { id: "Data-Infrastructure", title: "Data Infrastructure", category: "Engineering", filename: "ARG-Builder-Data-Infrastructure.md" },
  { id: "Data-Residency-Sovereignty", title: "Data Residency Sovereignty", category: "Strategy & Operations", filename: "ARG-Builder-Data-Residency-Sovereignty.md" },
  { id: "Database-Backup-Recovery", title: "Database Backup Recovery", category: "Engineering", filename: "ARG-Builder-Database-Backup-Recovery.md" },
  { id: "Database-Migration-Schema-Evolution", title: "Database Migration Schema Evolution", category: "Engineering", filename: "ARG-Builder-Database-Migration-Schema-Evolution.md" },
  { id: "Database-Strategy-Optimization", title: "Database Strategy Optimization", category: "Engineering", filename: "ARG-Builder-Database-Strategy-Optimization.md" },
  { id: "Demand-Gen", title: "Demand Gen", category: "Marketing", filename: "ARG-Builder-Demand-Gen.md" },
  { id: "Demand-Generation-Engine", title: "Demand Generation Engine", category: "Marketing", filename: "ARG-Builder-Demand-Generation-Engine.md" },
  { id: "Demo-Environment-Management", title: "Demo Environment Management", category: "Engineering", filename: "ARG-Builder-Demo-Environment-Management.md" },
  { id: "Dependency-Injection-IoC", title: "Dependency Injection IoC", category: "Engineering", filename: "ARG-Builder-Dependency-Injection-IoC.md" },
  { id: "Dependency-Supply-Chain-Security", title: "Dependency Supply Chain Security", category: "Engineering", filename: "ARG-Builder-Dependency-Supply-Chain-Security.md" },
  { id: "Design-System-Component-Library", title: "Design System Component Library", category: "Product", filename: "ARG-Builder-Design-System-Component-Library.md" },
  { id: "DevRel-Strategy", title: "DevRel Strategy", category: "Strategy & Operations", filename: "ARG-Builder-DevRel-Strategy.md" },
  { id: "Developer-Experience", title: "Developer Experience", category: "Strategy & Operations", filename: "ARG-Builder-Developer-Experience.md" },
  { id: "Digital-Adoption-Platform", title: "Digital Adoption Platform", category: "Engineering", filename: "ARG-Builder-Digital-Adoption-Platform.md" },
  { id: "Distributed-Systems-Patterns", title: "Distributed Systems Patterns", category: "People & Culture", filename: "ARG-Builder-Distributed-Systems-Patterns.md" },
  { id: "Downsell-Churn-Prevention", title: "Downsell Churn Prevention", category: "Customer Success", filename: "ARG-Builder-Downsell-Churn-Prevention.md" },
  { id: "Drag-Drop-Visual-Builder", title: "Drag Drop Visual Builder", category: "Product", filename: "ARG-Builder-Drag-Drop-Visual-Builder.md" },
  { id: "Due-Diligence-Prep", title: "Due Diligence Prep", category: "Strategy & Operations", filename: "ARG-Builder-Due-Diligence-Prep.md" },
  { id: "ESOP-Administration", title: "ESOP Administration", category: "Finance & Legal", filename: "ARG-Builder-ESOP-Administration.md" },
  { id: "ESOP", title: "ESOP", category: "Finance & Legal", filename: "ARG-Builder-ESOP.md" },
  { id: "Edge-Function-Serverless-Middleware", title: "Edge Function Serverless Middleware", category: "Engineering", filename: "ARG-Builder-Edge-Function-Serverless-Middleware.md" },
  { id: "Email-Deliverability-Architecture", title: "Email Deliverability Architecture", category: "Engineering", filename: "ARG-Builder-Email-Deliverability-Architecture.md" },
  { id: "Email-Marketing-Drip-Campaigns", title: "Email Marketing Drip Campaigns", category: "Marketing", filename: "ARG-Builder-Email-Marketing-Drip-Campaigns.md" },
  { id: "Email-Template-Design-System", title: "Email Template Design System", category: "Marketing", filename: "ARG-Builder-Email-Template-Design-System.md" },
  { id: "Employee-Handbook-Policies", title: "Employee Handbook Policies", category: "Strategy & Operations", filename: "ARG-Builder-Employee-Handbook-Policies.md" },
  { id: "Employee-Handbook", title: "Employee Handbook", category: "Strategy & Operations", filename: "ARG-Builder-Employee-Handbook.md" },
  { id: "Employee-Onboarding", title: "Employee Onboarding", category: "Customer Success", filename: "ARG-Builder-Employee-Onboarding.md" },
  { id: "Engineering-Assessments", title: "Engineering Assessments", category: "Engineering", filename: "ARG-Builder-Engineering-Assessments.md" },
  { id: "Engineering-Automated-Canary-Analysis-and-Progressive-Rollout", title: "Engineering Automated Canary Analysis and Progressive Rollout", category: "Engineering", filename: "ARG-Builder-Engineering-Automated-Canary-Analysis-and-Progressive-Rollout.md" },
  { id: "Engineering-Automated-Code-Generation-AI-Assisted-Development", title: "Engineering Automated Code Generation AI Assisted Development", category: "Engineering", filename: "ARG-Builder-Engineering-Automated-Code-Generation-AI-Assisted-Development.md" },
  { id: "Engineering-Automated-Documentation-Generation-and-Maintenance", title: "Engineering Automated Documentation Generation and Maintenance", category: "Engineering", filename: "ARG-Builder-Engineering-Automated-Documentation-Generation-and-Maintenance.md" },
  { id: "Engineering-Automated-Infrastructure-Cost-Alerting-and-FinOps-Dashboard", title: "Engineering Automated Infrastructure Cost Alerting and FinOps Dashboard", category: "Engineering", filename: "ARG-Builder-Engineering-Automated-Infrastructure-Cost-Alerting-and-FinOps-Dashboard.md" },
  { id: "Engineering-Automated-Regression-Testing-and-Visual-Snapshot-Testing", title: "Engineering Automated Regression Testing and Visual Snapshot Testing", category: "Engineering", filename: "ARG-Builder-Engineering-Automated-Regression-Testing-and-Visual-Snapshot-Testing.md" },
  { id: "Engineering-Automated-Security-Scanning-and-DevSecOps-Pipeline", title: "Engineering Automated Security Scanning and DevSecOps Pipeline", category: "Engineering", filename: "ARG-Builder-Engineering-Automated-Security-Scanning-and-DevSecOps-Pipeline.md" },
  { id: "Engineering-Capacity-Planning", title: "Engineering Capacity Planning", category: "Engineering", filename: "ARG-Builder-Engineering-Capacity-Planning.md" },
  { id: "Engineering-Chaos-Engineering-and-Resilience-Testing", title: "Engineering Chaos Engineering and Resilience Testing", category: "Engineering", filename: "ARG-Builder-Engineering-Chaos-Engineering-and-Resilience-Testing.md" },
  { id: "Engineering-Culture", title: "Engineering Culture", category: "Engineering", filename: "ARG-Builder-Engineering-Culture.md" },
  { id: "Engineering-Debt-Prioritization", title: "Engineering Debt Prioritization", category: "Engineering", filename: "ARG-Builder-Engineering-Debt-Prioritization.md" },
  { id: "Engineering-Deployment-Environments-Preview-Deployments", title: "Engineering Deployment Environments Preview Deployments", category: "Engineering", filename: "ARG-Builder-Engineering-Deployment-Environments-Preview-Deployments.md" },
  { id: "Engineering-Edge-Computing-and-CDN-Strategy", title: "Engineering Edge Computing and CDN Strategy", category: "Engineering", filename: "ARG-Builder-Engineering-Edge-Computing-and-CDN-Strategy.md" },
  { id: "Engineering-Feature-Parity-Matrix-and-Cross-Platform-Strategy", title: "Engineering Feature Parity Matrix and Cross Platform Strategy", category: "Engineering", filename: "ARG-Builder-Engineering-Feature-Parity-Matrix-and-Cross-Platform-Strategy.md" },
  { id: "Engineering-Interview-System", title: "Engineering Interview System", category: "Engineering", filename: "ARG-Builder-Engineering-Interview-System.md" },
  { id: "Engineering-Monolith-Decomposition-Patterns", title: "Engineering Monolith Decomposition Patterns", category: "Engineering", filename: "ARG-Builder-Engineering-Monolith-Decomposition-Patterns.md" },
  { id: "Engineering-Observability-Driven-Development-A-Comprehensive-Guide-for-ARG-Build", title: "Engineering Observability Driven Development A Comprehensive Guide for ARG Build", category: "Engineering", filename: "ARG-Builder-Engineering-Observability-Driven-Development-A-Comprehensive-Guide-for-ARG-Build.md" },
  { id: "Engineering-OnCall-Reliability", title: "Engineering OnCall Reliability", category: "Engineering", filename: "ARG-Builder-Engineering-OnCall-Reliability.md" },
  { id: "Engineering-OpenTelemetry-Implementation-and-Distributed-Tracing", title: "Engineering OpenTelemetry Implementation and Distributed Tracing", category: "Engineering", filename: "ARG-Builder-Engineering-OpenTelemetry-Implementation-and-Distributed-Tracing.md" },
  { id: "Engineering-Platform-Team-Charter", title: "Engineering Platform Team Charter", category: "Engineering", filename: "ARG-Builder-Engineering-Platform-Team-Charter.md" },
  { id: "Engineering-Real-Time-Collaboration-CRDT-Implementation-Guide", title: "Engineering Real Time Collaboration CRDT Implementation Guide", category: "Engineering", filename: "ARG-Builder-Engineering-Real-Time-Collaboration-CRDT-Implementation-Guide.md" },
  { id: "Engineering-Runbook-Library", title: "Engineering Runbook Library", category: "Engineering", filename: "ARG-Builder-Engineering-Runbook-Library.md" },
  { id: "Engineering-Technical-Program-Management-TPM", title: "Engineering Technical Program Management TPM", category: "Engineering", filename: "ARG-Builder-Engineering-Technical-Program-Management-TPM.md" },
  { id: "Engineering-Technical-Writing-Standards-and-Documentation-Culture", title: "Engineering Technical Writing Standards and Documentation Culture", category: "Engineering", filename: "ARG-Builder-Engineering-Technical-Writing-Standards-and-Documentation-Culture.md" },
  { id: "Engineering-Zero-Trust-Security-Architecture", title: "Engineering Zero Trust Security Architecture", category: "Engineering", filename: "ARG-Builder-Engineering-Zero-Trust-Security-Architecture.md" },
  { id: "Enterprise-Sales-Playbook", title: "Enterprise Sales Playbook", category: "Sales", filename: "ARG-Builder-Enterprise-Sales-Playbook.md" },
  { id: "Environment-Management-Configuration", title: "Environment Management Configuration", category: "Engineering", filename: "ARG-Builder-Environment-Management-Configuration.md" },
  { id: "Equity-Cap-Table-Management", title: "Equity Cap Table Management", category: "Finance & Legal", filename: "ARG-Builder-Equity-Cap-Table-Management.md" },
  { id: "Equity-Compensation", title: "Equity Compensation", category: "Finance & Legal", filename: "ARG-Builder-Equity-Compensation.md" },
  { id: "Error-Handling-Resilience", title: "Error Handling Resilience", category: "Engineering", filename: "ARG-Builder-Error-Handling-Resilience.md" },
  { id: "Event-Marketing-Field-Events", title: "Event Marketing Field Events", category: "Marketing", filename: "ARG-Builder-Event-Marketing-Field-Events.md" },
  { id: "Exit-Strategy", title: "Exit Strategy", category: "Strategy & Operations", filename: "ARG-Builder-Exit-Strategy.md" },
  { id: "Expansion-Revenue-Playbook", title: "Expansion Revenue Playbook", category: "Customer Success", filename: "ARG-Builder-Expansion-Revenue-Playbook.md" },
  { id: "Expansion-Revenue", title: "Expansion Revenue", category: "Customer Success", filename: "ARG-Builder-Expansion-Revenue.md" },
  { id: "FPA-Financial-Modeling", title: "FPA Financial Modeling", category: "Strategy & Operations", filename: "ARG-Builder-FPA-Financial-Modeling.md" },
  { id: "Feature-Adoption-Activation-Metrics", title: "Feature Adoption Activation Metrics", category: "Strategy & Operations", filename: "ARG-Builder-Feature-Adoption-Activation-Metrics.md" },
  { id: "Feature-Flagging-Experimentation", title: "Feature Flagging Experimentation", category: "Engineering", filename: "ARG-Builder-Feature-Flagging-Experimentation.md" },
  { id: "Feature-Prioritization", title: "Feature Prioritization", category: "Strategy & Operations", filename: "ARG-Builder-Feature-Prioritization.md" },
  { id: "Feature-Toggle-Management", title: "Feature Toggle Management", category: "Engineering", filename: "ARG-Builder-Feature-Toggle-Management.md" },
  { id: "Feedback-Loop", title: "Feedback Loop", category: "Customer Success", filename: "ARG-Builder-Feedback-Loop.md" },
  { id: "Feedback-Voting-Feature-Requests", title: "Feedback Voting Feature Requests", category: "Customer Success", filename: "ARG-Builder-Feedback-Voting-Feature-Requests.md" },
  { id: "File-Upload-Media-Processing", title: "File Upload Media Processing", category: "Strategy & Operations", filename: "ARG-Builder-File-Upload-Media-Processing.md" },
  { id: "Financial-Controls", title: "Financial Controls", category: "Strategy & Operations", filename: "ARG-Builder-Financial-Controls.md" },
  { id: "Financial-Model", title: "Financial Model", category: "Strategy & Operations", filename: "ARG-Builder-Financial-Model.md" },
  { id: "Form-Builder-Dynamic-Forms", title: "Form Builder Dynamic Forms", category: "Product", filename: "ARG-Builder-Form-Builder-Dynamic-Forms.md" },
  { id: "Founder-Mental-Health", title: "Founder Mental Health", category: "Strategy & Operations", filename: "ARG-Builder-Founder-Mental-Health.md" },
  { id: "Founder-Vesting-CoFounder-Agreements", title: "Founder Vesting CoFounder Agreements", category: "Strategy & Operations", filename: "ARG-Builder-Founder-Vesting-CoFounder-Agreements.md" },
  { id: "Founders-Operating-Manual", title: "Founders Operating Manual", category: "Strategy & Operations", filename: "ARG-Builder-Founders-Operating-Manual.md" },
  { id: "Founding-Customer-Playbook", title: "Founding Customer Playbook", category: "Customer Success", filename: "ARG-Builder-Founding-Customer-Playbook.md" },
  { id: "Frontend-Performance-Monitoring", title: "Frontend Performance Monitoring", category: "Engineering", filename: "ARG-Builder-Frontend-Performance-Monitoring.md" },
  { id: "Frontend-State-Management", title: "Frontend State Management", category: "Engineering", filename: "ARG-Builder-Frontend-State-Management.md" },
  { id: "Fundraising-Data-Room", title: "Fundraising Data Room", category: "Finance & Legal", filename: "ARG-Builder-Fundraising-Data-Room.md" },
  { id: "Fundraising-Toolkit", title: "Fundraising Toolkit", category: "Finance & Legal", filename: "ARG-Builder-Fundraising-Toolkit.md" },
  { id: "G2-Review-Site-Strategy", title: "G2 Review Site Strategy", category: "Strategy & Operations", filename: "ARG-Builder-G2-Review-Site-Strategy.md" },
  { id: "GTM-Partnerships-Channel", title: "GTM Partnerships Channel", category: "Partnerships & GTM", filename: "ARG-Builder-GTM-Partnerships-Channel.md" },
  { id: "GTM-Readiness", title: "GTM Readiness", category: "Partnerships & GTM", filename: "ARG-Builder-GTM-Readiness.md" },
  { id: "GTM-Sales-Strategy", title: "GTM Sales Strategy", category: "Sales", filename: "ARG-Builder-GTM-Sales-Strategy.md" },
  { id: "Git-Workflow-Branching", title: "Git Workflow Branching", category: "Engineering", filename: "ARG-Builder-Git-Workflow-Branching.md" },
  { id: "GraphQL-API-Strategy", title: "GraphQL API Strategy", category: "Engineering", filename: "ARG-Builder-GraphQL-API-Strategy.md" },
  { id: "GraphQL-Schema-Design-Federation", title: "GraphQL Schema Design Federation", category: "Engineering", filename: "ARG-Builder-GraphQL-Schema-Design-Federation.md" },
  { id: "Hiring-Playbook", title: "Hiring Playbook", category: "People & Culture", filename: "ARG-Builder-Hiring-Playbook.md" },
  { id: "IP-Strategy", title: "IP Strategy", category: "Finance & Legal", filename: "ARG-Builder-IP-Strategy.md" },
  { id: "Image-Asset-Pipeline", title: "Image Asset Pipeline", category: "Engineering", filename: "ARG-Builder-Image-Asset-Pipeline.md" },
  { id: "Implementation-Methodology", title: "Implementation Methodology", category: "Customer Success", filename: "ARG-Builder-Implementation-Methodology.md" },
  { id: "InApp-Messaging-Announcements", title: "InApp Messaging Announcements", category: "Marketing", filename: "ARG-Builder-InApp-Messaging-Announcements.md" },
  { id: "Incident-Command-System", title: "Incident Command System", category: "Operations", filename: "ARG-Builder-Incident-Command-System.md" },
  { id: "Incident-Management", title: "Incident Management", category: "Operations", filename: "ARG-Builder-Incident-Management.md" },
  { id: "Incident-Post-Mortem-Process", title: "Incident Post Mortem Process", category: "Operations", filename: "ARG-Builder-Incident-Post-Mortem-Process.md" },
  { id: "Influencer-Analyst-Relations", title: "Influencer Analyst Relations", category: "Marketing", filename: "ARG-Builder-Influencer-Analyst-Relations.md" },
  { id: "Infrastructure-as-Code", title: "Infrastructure as Code", category: "Engineering", filename: "ARG-Builder-Infrastructure-as-Code.md" },
  { id: "Insurance-Risk-Management", title: "Insurance Risk Management", category: "Finance & Legal", filename: "ARG-Builder-Insurance-Risk-Management.md" },
  { id: "Intellectual-Property-Strategy", title: "Intellectual Property Strategy", category: "Strategy & Operations", filename: "ARG-Builder-Intellectual-Property-Strategy.md" },
  { id: "Internal-Comms-Town-Hall", title: "Internal Comms Town Hall", category: "Strategy & Operations", filename: "ARG-Builder-Internal-Comms-Town-Hall.md" },
  { id: "Internal-Developer-Platform-IDP-Platform-Engineering", title: "Internal Developer Platform IDP Platform Engineering", category: "Engineering", filename: "ARG-Builder-Internal-Developer-Platform-IDP-Platform-Engineering.md" },
  { id: "International-Expansion", title: "International Expansion", category: "Customer Success", filename: "ARG-Builder-International-Expansion.md" },
  { id: "Internationalization-Technical", title: "Internationalization Technical", category: "Strategy & Operations", filename: "ARG-Builder-Internationalization-Technical.md" },
  { id: "Investor-Outreach", title: "Investor Outreach", category: "Finance & Legal", filename: "ARG-Builder-Investor-Outreach.md" },
  { id: "Investor-Pitch-Deck", title: "Investor Pitch Deck", category: "Finance & Legal", filename: "ARG-Builder-Investor-Pitch-Deck.md" },
  { id: "Investor-Relations-Dashboard", title: "Investor Relations Dashboard", category: "Finance & Legal", filename: "ARG-Builder-Investor-Relations-Dashboard.md" },
  { id: "Investor-Relations-Fundraising", title: "Investor Relations Fundraising", category: "Finance & Legal", filename: "ARG-Builder-Investor-Relations-Fundraising.md" },
  { id: "Investor-Relations", title: "Investor Relations", category: "Finance & Legal", filename: "ARG-Builder-Investor-Relations.md" },
  { id: "Investor-Update", title: "Investor Update", category: "Finance & Legal", filename: "ARG-Builder-Investor-Update.md" },
  { id: "Invoice-Payment-Operations", title: "Invoice Payment Operations", category: "Strategy & Operations", filename: "ARG-Builder-Invoice-Payment-Operations.md" },
  { id: "Keyboard-First-Power-User-UX", title: "Keyboard First Power User UX", category: "Product", filename: "ARG-Builder-Keyboard-First-Power-User-UX.md" },
  { id: "Keyboard-Shortcuts-Power-User", title: "Keyboard Shortcuts Power User", category: "Product", filename: "ARG-Builder-Keyboard-Shortcuts-Power-User.md" },
  { id: "Knowledge-Management-Wiki", title: "Knowledge Management Wiki", category: "Strategy & Operations", filename: "ARG-Builder-Knowledge-Management-Wiki.md" },
  { id: "Knowledge-Management", title: "Knowledge Management", category: "Strategy & Operations", filename: "ARG-Builder-Knowledge-Management.md" },
  { id: "LTV-Modeling-Optimization", title: "LTV Modeling Optimization", category: "Strategy & Operations", filename: "ARG-Builder-LTV-Modeling-Optimization.md" },
  { id: "Landing-Page-Optimization-CRO", title: "Landing Page Optimization CRO", category: "Marketing", filename: "ARG-Builder-Landing-Page-Optimization-CRO.md" },
  { id: "Launch-Event-Strategy", title: "Launch Event Strategy", category: "Marketing", filename: "ARG-Builder-Launch-Event-Strategy.md" },
  { id: "Legal-Entity-Structure", title: "Legal Entity Structure", category: "Finance & Legal", filename: "ARG-Builder-Legal-Entity-Structure.md" },
  { id: "Legal-IP-Protection", title: "Legal IP Protection", category: "Finance & Legal", filename: "ARG-Builder-Legal-IP-Protection.md" },
  { id: "Legal-Package", title: "Legal Package", category: "Finance & Legal", filename: "ARG-Builder-Legal-Package.md" },
  { id: "Lifecycle-Emails", title: "Lifecycle Emails", category: "Customer Success", filename: "ARG-Builder-Lifecycle-Emails.md" },
  { id: "Lifecycle-Marketing-Automation", title: "Lifecycle Marketing Automation", category: "Customer Success", filename: "ARG-Builder-Lifecycle-Marketing-Automation.md" },
  { id: "LinkedIn-Marketing-Social-Selling", title: "LinkedIn Marketing Social Selling", category: "Marketing", filename: "ARG-Builder-LinkedIn-Marketing-Social-Selling.md" },
  { id: "Load-Testing-Performance-Benchmarking", title: "Load Testing Performance Benchmarking", category: "Engineering", filename: "ARG-Builder-Load-Testing-Performance-Benchmarking.md" },
  { id: "Localization-i18n", title: "Localization i18n", category: "Strategy & Operations", filename: "ARG-Builder-Localization-i18n.md" },
  { id: "Logging-Strategy-Structured-Logging", title: "Logging Strategy Structured Logging", category: "Engineering", filename: "ARG-Builder-Logging-Strategy-Structured-Logging.md" },
  { id: "MA-Readiness-Exit-Planning", title: "MA Readiness Exit Planning", category: "Strategy & Operations", filename: "ARG-Builder-MA-Readiness-Exit-Planning.md" },
  { id: "MA-Strategy", title: "MA Strategy", category: "Strategy & Operations", filename: "ARG-Builder-MA-Strategy.md" },
  { id: "MASTER-INDEX", title: "MASTER INDEX", category: "Strategy & Operations", filename: "ARG-Builder-MASTER-INDEX.md" },
  { id: "MVP-Roadmap", title: "MVP Roadmap", category: "Product", filename: "ARG-Builder-MVP-Roadmap.md" },
  { id: "Market-Expansion-Verticals", title: "Market Expansion Verticals", category: "Customer Success", filename: "ARG-Builder-Market-Expansion-Verticals.md" },
  { id: "Marketing-Attribution", title: "Marketing Attribution", category: "Marketing", filename: "ARG-Builder-Marketing-Attribution.md" },
  { id: "Marketing-Ops", title: "Marketing Ops", category: "Marketing", filename: "ARG-Builder-Marketing-Ops.md" },
  { id: "Marketplace-App-Store", title: "Marketplace App Store", category: "Partnerships & GTM", filename: "ARG-Builder-Marketplace-App-Store.md" },
  { id: "Marketplace-Listing-Optimization", title: "Marketplace Listing Optimization", category: "Partnerships & GTM", filename: "ARG-Builder-Marketplace-Listing-Optimization.md" },
  { id: "Memory-Management-Performance-Profiling", title: "Memory Management Performance Profiling", category: "Engineering", filename: "ARG-Builder-Memory-Management-Performance-Profiling.md" },
  { id: "Metrics-Dashboard", title: "Metrics Dashboard", category: "Strategy & Operations", filename: "ARG-Builder-Metrics-Dashboard.md" },
  { id: "Microservices-Migration", title: "Microservices Migration", category: "Engineering", filename: "ARG-Builder-Microservices-Migration.md" },
  { id: "Mobile-Responsiveness-PWA", title: "Mobile Responsiveness PWA", category: "Strategy & Operations", filename: "ARG-Builder-Mobile-Responsiveness-PWA.md" },
  { id: "Monolith-Modularization", title: "Monolith Modularization", category: "Strategy & Operations", filename: "ARG-Builder-Monolith-Modularization.md" },
  { id: "Monorepo-Build-Optimization", title: "Monorepo Build Optimization", category: "Engineering", filename: "ARG-Builder-Monorepo-Build-Optimization.md" },
  { id: "Monorepo-Polyrepo-Strategy", title: "Monorepo Polyrepo Strategy", category: "Engineering", filename: "ARG-Builder-Monorepo-Polyrepo-Strategy.md" },
  { id: "Multi-Language-Support-Ops", title: "Multi Language Support Ops", category: "Strategy & Operations", filename: "ARG-Builder-Multi-Language-Support-Ops.md" },
  { id: "Multi-Product-Cross-Sell", title: "Multi Product Cross Sell", category: "Product", filename: "ARG-Builder-Multi-Product-Cross-Sell.md" },
  { id: "Multi-Product-Strategy", title: "Multi Product Strategy", category: "Product", filename: "ARG-Builder-Multi-Product-Strategy.md" },
  { id: "Multi-Stakeholder-Deal-Navigation", title: "Multi Stakeholder Deal Navigation", category: "Sales", filename: "ARG-Builder-Multi-Stakeholder-Deal-Navigation.md" },
  { id: "Multi-Tenancy-Database-Patterns", title: "Multi Tenancy Database Patterns", category: "Engineering", filename: "ARG-Builder-Multi-Tenancy-Database-Patterns.md" },
  { id: "Multi-Tenant-Architecture", title: "Multi Tenant Architecture", category: "Engineering", filename: "ARG-Builder-Multi-Tenant-Architecture.md" },
  { id: "NPS-CSAT-Program", title: "NPS CSAT Program", category: "Customer Success", filename: "ARG-Builder-NPS-CSAT-Program.md" },
  { id: "Notification-Infrastructure-Preferences", title: "Notification Infrastructure Preferences", category: "Engineering", filename: "ARG-Builder-Notification-Infrastructure-Preferences.md" },
  { id: "Notification-Preferences-Quiet-Hours", title: "Notification Preferences Quiet Hours", category: "Product", filename: "ARG-Builder-Notification-Preferences-Quiet-Hours.md" },
  { id: "Notification-System-Design", title: "Notification System Design", category: "Product", filename: "ARG-Builder-Notification-System-Design.md" },
  { id: "OKR-Framework", title: "OKR Framework", category: "Strategy & Operations", filename: "ARG-Builder-OKR-Framework.md" },
  { id: "Objection-Library", title: "Objection Library", category: "Sales", filename: "ARG-Builder-Objection-Library.md" },
  { id: "Observability-Monitoring", title: "Observability Monitoring", category: "Engineering", filename: "ARG-Builder-Observability-Monitoring.md" },
  { id: "Office-Workspace-Strategy", title: "Office Workspace Strategy", category: "Strategy & Operations", filename: "ARG-Builder-Office-Workspace-Strategy.md" },
  { id: "Onboarding-Automation", title: "Onboarding Automation", category: "Customer Success", filename: "ARG-Builder-Onboarding-Automation.md" },
  { id: "Onboarding-Certification-Program", title: "Onboarding Certification Program", category: "Customer Success", filename: "ARG-Builder-Onboarding-Certification-Program.md" },
  { id: "Onboarding-Content-Library", title: "Onboarding Content Library", category: "Customer Success", filename: "ARG-Builder-Onboarding-Content-Library.md" },
  { id: "Onboarding-Email-Sequence", title: "Onboarding Email Sequence", category: "Customer Success", filename: "ARG-Builder-Onboarding-Email-Sequence.md" },
  { id: "Onboarding-Emails", title: "Onboarding Emails", category: "Customer Success", filename: "ARG-Builder-Onboarding-Emails.md" },
  { id: "Onboarding-Gamification", title: "Onboarding Gamification", category: "Customer Success", filename: "ARG-Builder-Onboarding-Gamification.md" },
  { id: "Onboarding-Kickoff-Meeting", title: "Onboarding Kickoff Meeting", category: "Customer Success", filename: "ARG-Builder-Onboarding-Kickoff-Meeting.md" },
  { id: "Operational-Efficiency", title: "Operational Efficiency", category: "Strategy & Operations", filename: "ARG-Builder-Operational-Efficiency.md" },
  { id: "Operations-Implementation", title: "Operations Implementation", category: "Customer Success", filename: "ARG-Builder-Operations-Implementation.md" },
  { id: "Outbound-Sales-Cadence", title: "Outbound Sales Cadence", category: "Sales", filename: "ARG-Builder-Outbound-Sales-Cadence.md" },
  { id: "PLG-Strategy", title: "PLG Strategy", category: "Strategy & Operations", filename: "ARG-Builder-PLG-Strategy.md" },
  { id: "POV-Pilot-Program-Design", title: "POV Pilot Program Design", category: "Sales", filename: "ARG-Builder-POV-Pilot-Program-Design.md" },
  { id: "Pagination-Infinite-Scroll", title: "Pagination Infinite Scroll", category: "Engineering", filename: "ARG-Builder-Pagination-Infinite-Scroll.md" },
  { id: "Paid-Advertising-Performance-Marketing", title: "Paid Advertising Performance Marketing", category: "Marketing", filename: "ARG-Builder-Paid-Advertising-Performance-Marketing.md" },
  { id: "Partner-Ecosystem", title: "Partner Ecosystem", category: "Partnerships & GTM", filename: "ARG-Builder-Partner-Ecosystem.md" },
  { id: "Partner-Program", title: "Partner Program", category: "Partnerships & GTM", filename: "ARG-Builder-Partner-Program.md" },
  { id: "Partnership-Package", title: "Partnership Package", category: "Finance & Legal", filename: "ARG-Builder-Partnership-Package.md" },
  { id: "Partnerships-Ecosystem", title: "Partnerships Ecosystem", category: "Partnerships & GTM", filename: "ARG-Builder-Partnerships-Ecosystem.md" },
  { id: "Payroll-Benefits-Administration", title: "Payroll Benefits Administration", category: "Finance & Legal", filename: "ARG-Builder-Payroll-Benefits-Administration.md" },
  { id: "Performance-Budgets-Web-Vitals", title: "Performance Budgets Web Vitals", category: "Engineering", filename: "ARG-Builder-Performance-Budgets-Web-Vitals.md" },
  { id: "Performance-Review-System", title: "Performance Review System", category: "Engineering", filename: "ARG-Builder-Performance-Review-System.md" },
  { id: "Performance-Review", title: "Performance Review", category: "Engineering", filename: "ARG-Builder-Performance-Review.md" },
  { id: "Permissions-RBAC-Design", title: "Permissions RBAC Design", category: "Product", filename: "ARG-Builder-Permissions-RBAC-Design.md" },
  { id: "Persona-Buyer-Journey", title: "Persona Buyer Journey", category: "Strategy & Operations", filename: "ARG-Builder-Persona-Buyer-Journey.md" },
  { id: "Pipeline-Velocity-Deal-Acceleration", title: "Pipeline Velocity Deal Acceleration", category: "Sales", filename: "ARG-Builder-Pipeline-Velocity-Deal-Acceleration.md" },
  { id: "Pitch-Deck-Slides-Content", title: "Pitch Deck Slides Content", category: "Marketing", filename: "ARG-Builder-Pitch-Deck-Slides-Content.md" },
  { id: "Podcast-Advertising-Sponsorship", title: "Podcast Advertising Sponsorship", category: "Marketing", filename: "ARG-Builder-Podcast-Advertising-Sponsorship.md" },
  { id: "Podcast-Audio-Strategy", title: "Podcast Audio Strategy", category: "Marketing", filename: "ARG-Builder-Podcast-Audio-Strategy.md" },
  { id: "Post-Mortem-Learning-Culture", title: "Post Mortem Learning Culture", category: "Strategy & Operations", filename: "ARG-Builder-Post-Mortem-Learning-Culture.md" },
  { id: "Pre-Seed-Angel-Round", title: "Pre Seed Angel Round", category: "Finance & Legal", filename: "ARG-Builder-Pre-Seed-Angel-Round.md" },
  { id: "Press-Kit", title: "Press Kit", category: "Marketing", filename: "ARG-Builder-Press-Kit.md" },
  { id: "Pricing-Experimentation", title: "Pricing Experimentation", category: "Product", filename: "ARG-Builder-Pricing-Experimentation.md" },
  { id: "Pricing-Financial-Models", title: "Pricing Financial Models", category: "Revenue & Pricing", filename: "ARG-Builder-Pricing-Financial-Models.md" },
  { id: "Pricing-Negotiation-Tactics", title: "Pricing Negotiation Tactics", category: "Sales", filename: "ARG-Builder-Pricing-Negotiation-Tactics.md" },
  { id: "Pricing-Page-Optimization", title: "Pricing Page Optimization", category: "Revenue & Pricing", filename: "ARG-Builder-Pricing-Page-Optimization.md" },
  { id: "Pricing-Page-Psychology-Conversion", title: "Pricing Page Psychology Conversion", category: "Revenue & Pricing", filename: "ARG-Builder-Pricing-Page-Psychology-Conversion.md" },
  { id: "Pricing-Page", title: "Pricing Page", category: "Revenue & Pricing", filename: "ARG-Builder-Pricing-Page.md" },
  { id: "Pricing-Psychology-Monetization", title: "Pricing Psychology Monetization", category: "Revenue & Pricing", filename: "ARG-Builder-Pricing-Psychology-Monetization.md" },
  { id: "Pricing-Validation", title: "Pricing Validation", category: "Revenue & Pricing", filename: "ARG-Builder-Pricing-Validation.md" },
  { id: "Procurement-Vendor-Negotiation", title: "Procurement Vendor Negotiation", category: "Sales", filename: "ARG-Builder-Procurement-Vendor-Negotiation.md" },
  { id: "Product-Accessibility-Audit-and-Remediation-Roadmap", title: "Product Accessibility Audit and Remediation Roadmap", category: "Product", filename: "ARG-Builder-Product-Accessibility-Audit-and-Remediation-Roadmap.md" },
  { id: "Product-Accessibility", title: "Product Accessibility", category: "Product", filename: "ARG-Builder-Product-Accessibility.md" },
  { id: "Product-Analytics", title: "Product Analytics", category: "Data & Analytics", filename: "ARG-Builder-Product-Analytics.md" },
  { id: "Product-Collaborative-Editing-and-Real-Time-Multiplayer-UX-Design", title: "Product Collaborative Editing and Real Time Multiplayer UX Design", category: "Product", filename: "ARG-Builder-Product-Collaborative-Editing-and-Real-Time-Multiplayer-UX-Design.md" },
  { id: "Product-Composable-Architecture-and-Headless-Design", title: "Product Composable Architecture and Headless Design", category: "Engineering", filename: "ARG-Builder-Product-Composable-Architecture-and-Headless-Design.md" },
  { id: "Product-Contextual-Help-and-In-App-Knowledge-Base-Architecture", title: "Product Contextual Help and In App Knowledge Base Architecture", category: "Product", filename: "ARG-Builder-Product-Contextual-Help-and-In-App-Knowledge-Base-Architecture.md" },
  { id: "Product-Deprecation", title: "Product Deprecation", category: "Product", filename: "ARG-Builder-Product-Deprecation.md" },
  { id: "Product-Differentiation", title: "Product Differentiation", category: "Product", filename: "ARG-Builder-Product-Differentiation.md" },
  { id: "Product-Growth-Loops-Architecture", title: "Product Growth Loops Architecture", category: "Product", filename: "ARG-Builder-Product-Growth-Loops-Architecture.md" },
  { id: "Product-Information-Architecture-Navigation-Design-A-Comprehensive-Strategy-for-", title: "Product Information Architecture Navigation Design A Comprehensive Strategy for ", category: "Product", filename: "ARG-Builder-Product-Information-Architecture-Navigation-Design-A-Comprehensive-Strategy-for-.md" },
  { id: "Product-Launch", title: "Product Launch", category: "Product", filename: "ARG-Builder-Product-Launch.md" },
  { id: "Product-Led-Onboarding-Activation-Science", title: "Product Led Onboarding Activation Science", category: "Customer Success", filename: "ARG-Builder-Product-Led-Onboarding-Activation-Science.md" },
  { id: "Product-Led-Onboarding-Personalization-Engine", title: "Product Led Onboarding Personalization Engine", category: "Product", filename: "ARG-Builder-Product-Led-Onboarding-Personalization-Engine.md" },
  { id: "Product-Led-Sales", title: "Product Led Sales", category: "Sales", filename: "ARG-Builder-Product-Led-Sales.md" },
  { id: "Product-Market-Fit", title: "Product Market Fit", category: "Product", filename: "ARG-Builder-Product-Market-Fit.md" },
  { id: "Product-Metrics", title: "Product Metrics", category: "Product", filename: "ARG-Builder-Product-Metrics.md" },
  { id: "Product-Prototype", title: "Product Prototype", category: "Product", filename: "ARG-Builder-Product-Prototype.md" },
  { id: "Product-Roadmap-Governance", title: "Product Roadmap Governance", category: "Product", filename: "ARG-Builder-Product-Roadmap-Governance.md" },
  { id: "Product-Security-Hardening", title: "Product Security Hardening", category: "Product", filename: "ARG-Builder-Product-Security-Hardening.md" },
  { id: "Product-Usage-Analytics", title: "Product Usage Analytics", category: "Product", filename: "ARG-Builder-Product-Usage-Analytics.md" },
  { id: "QBR-Deck-Templates", title: "QBR Deck Templates", category: "Customer Success", filename: "ARG-Builder-QBR-Deck-Templates.md" },
  { id: "QBR-Execution-Excellence", title: "QBR Execution Excellence", category: "Customer Success", filename: "ARG-Builder-QBR-Execution-Excellence.md" },
  { id: "QBR-Template", title: "QBR Template", category: "Customer Success", filename: "ARG-Builder-QBR-Template.md" },
  { id: "ROI-Calculator", title: "ROI Calculator", category: "Revenue & Pricing", filename: "ARG-Builder-ROI-Calculator.md" },
  { id: "Real-Time-Data-Streaming", title: "Real Time Data Streaming", category: "Strategy & Operations", filename: "ARG-Builder-Real-Time-Data-Streaming.md" },
  { id: "Realtime-Collaboration-Multiplayer", title: "Realtime Collaboration Multiplayer", category: "Product", filename: "ARG-Builder-Realtime-Collaboration-Multiplayer.md" },
  { id: "Referral-Program-Mechanics", title: "Referral Program Mechanics", category: "Partnerships & GTM", filename: "ARG-Builder-Referral-Program-Mechanics.md" },
  { id: "Referral-Program", title: "Referral Program", category: "Partnerships & GTM", filename: "ARG-Builder-Referral-Program.md" },
  { id: "Release-Management-Versioning", title: "Release Management Versioning", category: "Engineering", filename: "ARG-Builder-Release-Management-Versioning.md" },
  { id: "Remote-Team-Operations", title: "Remote Team Operations", category: "People & Culture", filename: "ARG-Builder-Remote-Team-Operations.md" },
  { id: "Renewal-Forecasting-Revenue-Prediction", title: "Renewal Forecasting Revenue Prediction", category: "Customer Success", filename: "ARG-Builder-Renewal-Forecasting-Revenue-Prediction.md" },
  { id: "Retention-Loyalty", title: "Retention Loyalty", category: "Customer Success", filename: "ARG-Builder-Retention-Loyalty.md" },
  { id: "Retention-Metrics-Deep-Dive", title: "Retention Metrics Deep Dive", category: "Customer Success", filename: "ARG-Builder-Retention-Metrics-Deep-Dive.md" },
  { id: "RevOps-Automation", title: "RevOps Automation", category: "Sales", filename: "ARG-Builder-RevOps-Automation.md" },
  { id: "RevOps-Framework", title: "RevOps Framework", category: "Sales", filename: "ARG-Builder-RevOps-Framework.md" },
  { id: "Revenue-Forecasting", title: "Revenue Forecasting", category: "Sales", filename: "ARG-Builder-Revenue-Forecasting.md" },
  { id: "Revenue-Recognition-ASC606", title: "Revenue Recognition ASC606", category: "Finance & Legal", filename: "ARG-Builder-Revenue-Recognition-ASC606.md" },
  { id: "Revenue-Recognition", title: "Revenue Recognition", category: "Finance & Legal", filename: "ARG-Builder-Revenue-Recognition.md" },
  { id: "Risk-Analysis", title: "Risk Analysis", category: "Strategy & Operations", filename: "ARG-Builder-Risk-Analysis.md" },
  { id: "Roadmap-Communication", title: "Roadmap Communication", category: "Product", filename: "ARG-Builder-Roadmap-Communication.md" },
  { id: "Round43-Doc1", title: "Round43 Doc1", category: "Strategy & Operations", filename: "ARG-Builder-Round43-Doc1.md" },
  { id: "Round43-Doc2", title: "Round43 Doc2", category: "Strategy & Operations", filename: "ARG-Builder-Round43-Doc2.md" },
  { id: "Round43-Doc3", title: "Round43 Doc3", category: "Strategy & Operations", filename: "ARG-Builder-Round43-Doc3.md" },
  { id: "Round43-Doc7", title: "Round43 Doc7", category: "Strategy & Operations", filename: "ARG-Builder-Round43-Doc7.md" },
  { id: "Round43-Doc9", title: "Round43 Doc9", category: "Strategy & Operations", filename: "ARG-Builder-Round43-Doc9.md" },
  { id: "SDR-Playbook", title: "SDR Playbook", category: "Sales", filename: "ARG-Builder-SDR-Playbook.md" },
  { id: "SEO-Content-Operations", title: "SEO Content Operations", category: "Marketing", filename: "ARG-Builder-SEO-Content-Operations.md" },
  { id: "SOC2-Roadmap", title: "SOC2 Roadmap", category: "Product", filename: "ARG-Builder-SOC2-Roadmap.md" },
  { id: "SSO-SAML-OIDC-Implementation", title: "SSO SAML OIDC Implementation", category: "Customer Success", filename: "ARG-Builder-SSO-SAML-OIDC-Implementation.md" },
  { id: "SaaS-AI-Powered-Customer-Support-Automation-Customer-Proactive-Outreach-Automation-and-Lifecycle-Triggers", title: "SaaS AI Powered Customer Support Automation Customer Proactive Outreach Automation and Lifecycle Triggers", category: "Customer Success", filename: "ARG-Builder-SaaS-AI-Powered-Customer-Support-Automation-Customer-Proactive-Outreach-Automation-and-Lifecycle-Triggers.md" },
  { id: "SaaS-AI-Powered-Customer-Support-Automation-and-Chatbot-Strategy", title: "SaaS AI Powered Customer Support Automation and Chatbot Strategy", category: "AI & Developer", filename: "ARG-Builder-SaaS-AI-Powered-Customer-Support-Automation-and-Chatbot-Strategy.md" },
  { id: "SaaS-AI-Powered-Customer-Support-Automation", title: "SaaS AI Powered Customer Support Automation", category: "Customer Success", filename: "ARG-Builder-SaaS-AI-Powered-Customer-Support-Automation.md" },
  { id: "SaaS-Agentic-Workflow-Orchestration-Startup-Employee-Stock-Purchase-Plan-ESPP-Design", title: "SaaS Agentic Workflow Orchestration Startup Employee Stock Purchase Plan ESPP Design", category: "AI & Developer", filename: "ARG-Builder-SaaS-Agentic-Workflow-Orchestration-Startup-Employee-Stock-Purchase-Plan-ESPP-Design.md" },
  { id: "SaaS-Agentic-Workflow-Orchestration-and-AI-Copilot-Design", title: "SaaS Agentic Workflow Orchestration and AI Copilot Design", category: "AI & Developer", filename: "ARG-Builder-SaaS-Agentic-Workflow-Orchestration-and-AI-Copilot-Design.md" },
  { id: "SaaS-Benchmarks", title: "SaaS Benchmarks", category: "Strategy & Operations", filename: "ARG-Builder-SaaS-Benchmarks.md" },
  { id: "SaaS-Compliance-as-Code-and-Policy-Automation", title: "SaaS Compliance as Code and Policy Automation", category: "Security & Compliance", filename: "ARG-Builder-SaaS-Compliance-as-Code-and-Policy-Automation.md" },
  { id: "SaaS-Customer-360-Unified-Data-Model", title: "SaaS Customer 360 Unified Data Model", category: "Data & Analytics", filename: "ARG-Builder-SaaS-Customer-360-Unified-Data-Model.md" },
  { id: "SaaS-Customer-360-and-Unified-Data-Model-Architecture", title: "SaaS Customer 360 and Unified Data Model Architecture", category: "Data & Analytics", filename: "ARG-Builder-SaaS-Customer-360-and-Unified-Data-Model-Architecture.md" },
  { id: "SaaS-Customer-Onboarding-Metrics-Benchmarks", title: "SaaS Customer Onboarding Metrics Benchmarks", category: "Customer Success", filename: "ARG-Builder-SaaS-Customer-Onboarding-Metrics-Benchmarks.md" },
  { id: "SaaS-Data-Lake-Architecture-and-Analytics-Engineering", title: "SaaS Data Lake Architecture and Analytics Engineering", category: "Engineering", filename: "ARG-Builder-SaaS-Data-Lake-Architecture-and-Analytics-Engineering.md" },
  { id: "SaaS-Data-Mesh-Architecture-and-Decentralized-Data-Ownership", title: "SaaS Data Mesh Architecture and Decentralized Data Ownership", category: "Engineering", filename: "ARG-Builder-SaaS-Data-Mesh-Architecture-and-Decentralized-Data-Ownership.md" },
  { id: "SaaS-Embedded-Analytics-White-Label-BI-for-Customers", title: "SaaS Embedded Analytics White Label BI for Customers", category: "Data & Analytics", filename: "ARG-Builder-SaaS-Embedded-Analytics-White-Label-BI-for-Customers.md" },
  { id: "SaaS-Embedded-Payments-and-FinTech-Integration", title: "SaaS Embedded Payments and FinTech Integration", category: "Revenue & Pricing", filename: "ARG-Builder-SaaS-Embedded-Payments-and-FinTech-Integration.md" },
  { id: "SaaS-Enterprise-Feature-Gating-and-Tiered-Access-Control-Architecture", title: "SaaS Enterprise Feature Gating and Tiered Access Control Architecture", category: "Revenue & Pricing", filename: "ARG-Builder-SaaS-Enterprise-Feature-Gating-and-Tiered-Access-Control-Architecture.md" },
  { id: "SaaS-Horizontal-vs-Vertical-Platform-Strategy-Decision-Framework", title: "SaaS Horizontal vs Vertical Platform Strategy Decision Framework", category: "Strategy & Operations", filename: "ARG-Builder-SaaS-Horizontal-vs-Vertical-Platform-Strategy-Decision-Framework.md" },
  { id: "SaaS-Metrics-Glossary", title: "SaaS Metrics Glossary", category: "Strategy & Operations", filename: "ARG-Builder-SaaS-Metrics-Glossary.md" },
  { id: "SaaS-Multi-Region-Architecture-Global-Deployment", title: "SaaS Multi Region Architecture Global Deployment", category: "Engineering", filename: "ARG-Builder-SaaS-Multi-Region-Architecture-Global-Deployment.md" },
  { id: "SaaS-Multi-Tenant-Rate-Limiting-and-Fair-Usage-Policy", title: "SaaS Multi Tenant Rate Limiting and Fair Usage Policy", category: "Security & Compliance", filename: "ARG-Builder-SaaS-Multi-Tenant-Rate-Limiting-and-Fair-Usage-Policy.md" },
  { id: "SaaS-Platform-Ecosystem-and-Integration-Marketplace-Architecture", title: "SaaS Platform Ecosystem and Integration Marketplace Architecture", category: "Partnerships & GTM", filename: "ARG-Builder-SaaS-Platform-Ecosystem-and-Integration-Marketplace-Architecture.md" },
  { id: "SaaS-Pricing-Experimentation-Dynamic-Pricing-Strategy", title: "SaaS Pricing Experimentation Dynamic Pricing Strategy", category: "Product", filename: "ARG-Builder-SaaS-Pricing-Experimentation-Dynamic-Pricing-Strategy.md" },
  { id: "SaaS-Revenue-Intelligence-Deal-Analytics", title: "SaaS Revenue Intelligence Deal Analytics", category: "Sales", filename: "ARG-Builder-SaaS-Revenue-Intelligence-Deal-Analytics.md" },
  { id: "SaaS-Sustainability-and-Green-Software-Engineering", title: "SaaS Sustainability and Green Software Engineering", category: "Strategy & Operations", filename: "ARG-Builder-SaaS-Sustainability-and-Green-Software-Engineering.md" },
  { id: "SaaS-Tax-Strategy", title: "SaaS Tax Strategy", category: "Finance & Legal", filename: "ARG-Builder-SaaS-Tax-Strategy.md" },
  { id: "SaaS-Unit-Economics", title: "SaaS Unit Economics", category: "Revenue & Pricing", filename: "ARG-Builder-SaaS-Unit-Economics.md" },
  { id: "SaaS-Vertical-AI-Agent-Strategy", title: "SaaS Vertical AI Agent Strategy", category: "AI & Developer", filename: "ARG-Builder-SaaS-Vertical-AI-Agent-Strategy.md" },
  { id: "SaaS-Vertical-Market-Compliance-HIPAA-FedRAMP-SOX-Playbook", title: "SaaS Vertical Market Compliance HIPAA FedRAMP SOX Playbook", category: "Security & Compliance", filename: "ARG-Builder-SaaS-Vertical-Market-Compliance-HIPAA-FedRAMP-SOX-Playbook.md" },
  { id: "SaaS-Voice-of-Employee-Program", title: "SaaS Voice of Employee Program", category: "Strategy & Operations", filename: "ARG-Builder-SaaS-Voice-of-Employee-Program.md" },
  { id: "SaaS-Workflow-Automation-No-Code-Integration-Strategy", title: "SaaS Workflow Automation No Code Integration Strategy", category: "Engineering", filename: "ARG-Builder-SaaS-Workflow-Automation-No-Code-Integration-Strategy.md" },
  { id: "Sales-Collateral", title: "Sales Collateral", category: "Sales", filename: "ARG-Builder-Sales-Collateral.md" },
  { id: "Sales-Commission-Automation", title: "Sales Commission Automation", category: "Sales", filename: "ARG-Builder-Sales-Commission-Automation.md" },
  { id: "Sales-Compensation", title: "Sales Compensation", category: "Sales", filename: "ARG-Builder-Sales-Compensation.md" },
  { id: "Sales-Deal-Desk", title: "Sales Deal Desk", category: "Sales", filename: "ARG-Builder-Sales-Deal-Desk.md" },
  { id: "Sales-Demo-Methodology", title: "Sales Demo Methodology", category: "Sales", filename: "ARG-Builder-Sales-Demo-Methodology.md" },
  { id: "Sales-Demo", title: "Sales Demo", category: "Sales", filename: "ARG-Builder-Sales-Demo.md" },
  { id: "Sales-Discovery-Framework", title: "Sales Discovery Framework", category: "Sales", filename: "ARG-Builder-Sales-Discovery-Framework.md" },
  { id: "Sales-Email-Copywriting", title: "Sales Email Copywriting", category: "Sales", filename: "ARG-Builder-Sales-Email-Copywriting.md" },
  { id: "Sales-Enablement-Content", title: "Sales Enablement Content", category: "Sales", filename: "ARG-Builder-Sales-Enablement-Content.md" },
  { id: "Sales-Enablement", title: "Sales Enablement", category: "Sales", filename: "ARG-Builder-Sales-Enablement.md" },
  { id: "Sales-Engineering-Playbook", title: "Sales Engineering Playbook", category: "Engineering", filename: "ARG-Builder-Sales-Engineering-Playbook.md" },
  { id: "Sales-Enterprise-Procurement-Navigation-and-RFP-Response-System", title: "Sales Enterprise Procurement Navigation and RFP Response System", category: "Sales", filename: "ARG-Builder-Sales-Enterprise-Procurement-Navigation-and-RFP-Response-System.md" },
  { id: "Sales-Forecasting-Methodology", title: "Sales Forecasting Methodology", category: "Sales", filename: "ARG-Builder-Sales-Forecasting-Methodology.md" },
  { id: "Sales-Forecasting-Pipeline", title: "Sales Forecasting Pipeline", category: "Sales", filename: "ARG-Builder-Sales-Forecasting-Pipeline.md" },
  { id: "Sales-Forecasting", title: "Sales Forecasting", category: "Sales", filename: "ARG-Builder-Sales-Forecasting.md" },
  { id: "Sales-Handoff-AE-Onboarding", title: "Sales Handoff AE Onboarding", category: "Sales", filename: "ARG-Builder-Sales-Handoff-AE-Onboarding.md" },
  { id: "Sales-Intent-Data-Strategy-and-Buyer-Signal-Detection", title: "Sales Intent Data Strategy and Buyer Signal Detection", category: "Sales", filename: "ARG-Builder-Sales-Intent-Data-Strategy-and-Buyer-Signal-Detection.md" },
  { id: "Sales-Mutual-Action-Plans", title: "Sales Mutual Action Plans", category: "Sales", filename: "ARG-Builder-Sales-Mutual-Action-Plans.md" },
  { id: "Sales-Negotiation-Psychology-Closing-Techniques", title: "Sales Negotiation Psychology Closing Techniques", category: "Sales", filename: "ARG-Builder-Sales-Negotiation-Psychology-Closing-Techniques.md" },
  { id: "Sales-Objection-Handling", title: "Sales Objection Handling", category: "Sales", filename: "ARG-Builder-Sales-Objection-Handling.md" },
  { id: "Sales-Proof-of-Concept-Scoring-Model", title: "Sales Proof of Concept Scoring Model", category: "Sales", filename: "ARG-Builder-Sales-Proof-of-Concept-Scoring-Model.md" },
  { id: "Sales-Proposal-SOW-Automation", title: "Sales Proposal SOW Automation", category: "Sales", filename: "ARG-Builder-Sales-Proposal-SOW-Automation.md" },
  { id: "Sales-Revenue-Intelligence-and-Conversation-Analytics", title: "Sales Revenue Intelligence and Conversation Analytics", category: "Sales", filename: "ARG-Builder-Sales-Revenue-Intelligence-and-Conversation-Analytics.md" },
  { id: "Sales-Revenue-Operations-RevOps-Tech-Stack-and-Workflow-Design", title: "Sales Revenue Operations RevOps Tech Stack and Workflow Design", category: "Sales", filename: "ARG-Builder-Sales-Revenue-Operations-RevOps-Tech-Stack-and-Workflow-Design.md" },
  { id: "Sales-Territory-Planning", title: "Sales Territory Planning", category: "Sales", filename: "ARG-Builder-Sales-Territory-Planning.md" },
  { id: "Sales-Territory", title: "Sales Territory", category: "Sales", filename: "ARG-Builder-Sales-Territory.md" },
  { id: "Sales-Win-Loss-Analysis-Program-and-Competitive-Intelligence", title: "Sales Win Loss Analysis Program and Competitive Intelligence", category: "Sales", filename: "ARG-Builder-Sales-Win-Loss-Analysis-Program-and-Competitive-Intelligence.md" },
  { id: "Sandbox-Trial-Environment", title: "Sandbox Trial Environment", category: "Engineering", filename: "ARG-Builder-Sandbox-Trial-Environment.md" },
  { id: "Satisfaction-Survey-Design-Analysis", title: "Satisfaction Survey Design Analysis", category: "Customer Success", filename: "ARG-Builder-Satisfaction-Survey-Design-Analysis.md" },
  { id: "Satisfaction-Survey-Design", title: "Satisfaction Survey Design", category: "Customer Success", filename: "ARG-Builder-Satisfaction-Survey-Design.md" },
  { id: "Scalability-Infrastructure", title: "Scalability Infrastructure", category: "Engineering", filename: "ARG-Builder-Scalability-Infrastructure.md" },
  { id: "Search-Architecture-Full-Text", title: "Search Architecture Full Text", category: "Engineering", filename: "ARG-Builder-Search-Architecture-Full-Text.md" },
  { id: "Search-Discovery-UX", title: "Search Discovery UX", category: "Sales", filename: "ARG-Builder-Search-Discovery-UX.md" },
  { id: "Secrets-Configuration-Management", title: "Secrets Configuration Management", category: "Engineering", filename: "ARG-Builder-Secrets-Configuration-Management.md" },
  { id: "Secrets-Rotation-Zero-Trust", title: "Secrets Rotation Zero Trust", category: "Engineering", filename: "ARG-Builder-Secrets-Rotation-Zero-Trust.md" },
  { id: "Security-Compliance-SOC2-ISO", title: "Security Compliance SOC2 ISO", category: "Security & Compliance", filename: "ARG-Builder-Security-Compliance-SOC2-ISO.md" },
  { id: "Security-Incident-Response", title: "Security Incident Response", category: "Security & Compliance", filename: "ARG-Builder-Security-Incident-Response.md" },
  { id: "Seed-Round-Fundraising", title: "Seed Round Fundraising", category: "Finance & Legal", filename: "ARG-Builder-Seed-Round-Fundraising.md" },
  { id: "Segmentation-Product-Led-Growth", title: "Segmentation Product Led Growth", category: "Product", filename: "ARG-Builder-Segmentation-Product-Led-Growth.md" },
  { id: "Self-Service-Portal", title: "Self Service Portal", category: "Customer Success", filename: "ARG-Builder-Self-Service-Portal.md" },
  { id: "Series-A-Readiness", title: "Series A Readiness", category: "Finance & Legal", filename: "ARG-Builder-Series-A-Readiness.md" },
  { id: "Series-B-Preparation-Growth", title: "Series B Preparation Growth", category: "Finance & Legal", filename: "ARG-Builder-Series-B-Preparation-Growth.md" },
  { id: "Serverless-Edge-Computing", title: "Serverless Edge Computing", category: "Engineering", filename: "ARG-Builder-Serverless-Edge-Computing.md" },
  { id: "Session-Management-Auth-Architecture", title: "Session Management Auth Architecture", category: "Engineering", filename: "ARG-Builder-Session-Management-Auth-Architecture.md" },
  { id: "Social-Proof-Playbook", title: "Social Proof Playbook", category: "Marketing", filename: "ARG-Builder-Social-Proof-Playbook.md" },
  { id: "Startup-Board-Reporting-Dashboard-and-Investor-Update-Automation", title: "Startup Board Reporting Dashboard and Investor Update Automation", category: "Finance & Legal", filename: "ARG-Builder-Startup-Board-Reporting-Dashboard-and-Investor-Update-Automation.md" },
  { id: "Startup-CFO-Hiring-and-Finance-Team-Building-A-Comprehensive-Guide", title: "Startup CFO Hiring and Finance Team Building A Comprehensive Guide", category: "Finance & Legal", filename: "ARG-Builder-Startup-CFO-Hiring-and-Finance-Team-Building-A-Comprehensive-Guide.md" },
  { id: "Startup-Debt-Financing-Revenue-Based-Financing", title: "Startup Debt Financing Revenue Based Financing", category: "Strategy & Operations", filename: "ARG-Builder-Startup-Debt-Financing-Revenue-Based-Financing.md" },
  { id: "Startup-Secondaries-Market-and-Liquidity-Events", title: "Startup Secondaries Market and Liquidity Events", category: "Finance & Legal", filename: "ARG-Builder-Startup-Secondaries-Market-and-Liquidity-Events.md" },
  { id: "Startup-Storytelling-Narrative-Strategy-A-Comprehensive-Guide-for-ARG-Builder", title: "Startup Storytelling Narrative Strategy A Comprehensive Guide for ARG Builder", category: "Product", filename: "ARG-Builder-Startup-Storytelling-Narrative-Strategy-A-Comprehensive-Guide-for-ARG-Builder.md" },
  { id: "Status-Page-Uptime-Communication", title: "Status Page Uptime Communication", category: "Strategy & Operations", filename: "ARG-Builder-Status-Page-Uptime-Communication.md" },
  { id: "Strategic-Account-Management", title: "Strategic Account Management", category: "Strategy & Operations", filename: "ARG-Builder-Strategic-Account-Management.md" },
  { id: "Strategic-Planning-OKRs", title: "Strategic Planning OKRs", category: "Strategy & Operations", filename: "ARG-Builder-Strategic-Planning-OKRs.md" },
  { id: "Support-Operations", title: "Support Operations", category: "Strategy & Operations", filename: "ARG-Builder-Support-Operations.md" },
  { id: "Sustainability-CSR", title: "Sustainability CSR", category: "Strategy & Operations", filename: "ARG-Builder-Sustainability-CSR.md" },
  { id: "Talent-Acquisition", title: "Talent Acquisition", category: "People & Culture", filename: "ARG-Builder-Talent-Acquisition.md" },
  { id: "Talent-Retention", title: "Talent Retention", category: "Customer Success", filename: "ARG-Builder-Talent-Retention.md" },
  { id: "Team-Communication", title: "Team Communication", category: "Strategy & Operations", filename: "ARG-Builder-Team-Communication.md" },
  { id: "Team-Offsite-Retreat-Planning", title: "Team Offsite Retreat Planning", category: "Strategy & Operations", filename: "ARG-Builder-Team-Offsite-Retreat-Planning.md" },
  { id: "Tech-Stack-Guide", title: "Tech Stack Guide", category: "Strategy & Operations", filename: "ARG-Builder-Tech-Stack-Guide.md" },
  { id: "Technical-Architecture", title: "Technical Architecture", category: "Engineering", filename: "ARG-Builder-Technical-Architecture.md" },
  { id: "Technical-Debt", title: "Technical Debt", category: "Strategy & Operations", filename: "ARG-Builder-Technical-Debt.md" },
  { id: "Tenant-Onboarding-Provisioning", title: "Tenant Onboarding Provisioning", category: "Customer Success", filename: "ARG-Builder-Tenant-Onboarding-Provisioning.md" },
  { id: "Territory-Design-Quota-Setting", title: "Territory Design Quota Setting", category: "Sales", filename: "ARG-Builder-Territory-Design-Quota-Setting.md" },
  { id: "Testimonial-System", title: "Testimonial System", category: "Strategy & Operations", filename: "ARG-Builder-Testimonial-System.md" },
  { id: "Testing-Strategy-QA", title: "Testing Strategy QA", category: "Engineering", filename: "ARG-Builder-Testing-Strategy-QA.md" },
  { id: "Thought-Leadership", title: "Thought Leadership", category: "Finance & Legal", filename: "ARG-Builder-Thought-Leadership.md" },
  { id: "TypeScript-Best-Practices", title: "TypeScript Best Practices", category: "Engineering", filename: "ARG-Builder-TypeScript-Best-Practices.md" },
  { id: "Undo-Redo-Version-History", title: "Undo Redo Version History", category: "Product", filename: "ARG-Builder-Undo-Redo-Version-History.md" },
  { id: "Unit-Economics-Deep-Dive", title: "Unit Economics Deep Dive", category: "Revenue & Pricing", filename: "ARG-Builder-Unit-Economics-Deep-Dive.md" },
  { id: "Upsell-Trigger-Engine", title: "Upsell Trigger Engine", category: "Customer Success", filename: "ARG-Builder-Upsell-Trigger-Engine.md" },
  { id: "Usage-Based-Billing", title: "Usage Based Billing", category: "Finance & Legal", filename: "ARG-Builder-Usage-Based-Billing.md" },
  { id: "Vendor-Management", title: "Vendor Management", category: "Strategy & Operations", filename: "ARG-Builder-Vendor-Management.md" },
  { id: "Vendor-Procurement", title: "Vendor Procurement", category: "Strategy & Operations", filename: "ARG-Builder-Vendor-Procurement.md" },
  { id: "Venture-Debt-Alternative-Financing", title: "Venture Debt Alternative Financing", category: "Finance & Legal", filename: "ARG-Builder-Venture-Debt-Alternative-Financing.md" },
  { id: "Vertical-GTM", title: "Vertical GTM", category: "Partnerships & GTM", filename: "ARG-Builder-Vertical-GTM.md" },
  { id: "Video-Marketing-YouTube", title: "Video Marketing YouTube", category: "Marketing", filename: "ARG-Builder-Video-Marketing-YouTube.md" },
  { id: "WebSocket-Real-Time-Communication", title: "WebSocket Real Time Communication", category: "Strategy & Operations", filename: "ARG-Builder-WebSocket-Real-Time-Communication.md" },
  { id: "Webhook-Design-Delivery", title: "Webhook Design Delivery", category: "Engineering", filename: "ARG-Builder-Webhook-Design-Delivery.md" },
  { id: "Webhook-Event-Architecture", title: "Webhook Event Architecture", category: "Engineering", filename: "ARG-Builder-Webhook-Event-Architecture.md" },
  { id: "Webinar-Strategy-Execution", title: "Webinar Strategy Execution", category: "Marketing", filename: "ARG-Builder-Webinar-Strategy-Execution.md" },
  { id: "Webinar-Virtual-Event-Strategy", title: "Webinar Virtual Event Strategy", category: "Marketing", filename: "ARG-Builder-Webinar-Virtual-Event-Strategy.md" },
  { id: "White-Labeling-OEM", title: "White Labeling OEM", category: "Partnerships & GTM", filename: "ARG-Builder-White-Labeling-OEM.md" },
  { id: "Win-Loss-Analysis", title: "Win Loss Analysis", category: "Sales", filename: "ARG-Builder-Win-Loss-Analysis.md" },
  { id: "Workspace-Multi-Workspace", title: "Workspace Multi Workspace", category: "Strategy & Operations", filename: "ARG-Builder-Workspace-Multi-Workspace.md" },
  { id: "api-versioning-deprecation-strategy", title: "api versioning deprecation strategy", category: "Engineering", filename: "ARG-Builder-api-versioning-deprecation-strategy.md" },
  { id: "content-operations", title: "content operations", category: "Marketing", filename: "ARG-Builder-content-operations.md" },
  { id: "customer-digital-onboarding-flows-activation-metrics", title: "customer digital onboarding flows activation metrics", category: "Customer Success", filename: "ARG-Builder-customer-digital-onboarding-flows-activation-metrics.md" },
  { id: "customer-dx-optimization", title: "customer dx optimization", category: "Customer Success", filename: "ARG-Builder-customer-dx-optimization.md" },
  { id: "customer-outcome-based-success-management", title: "customer outcome based success management", category: "Customer Success", filename: "ARG-Builder-customer-outcome-based-success-management.md" },
  { id: "customer-proactive-support", title: "customer proactive support", category: "Customer Success", filename: "ARG-Builder-customer-proactive-support.md" },
  { id: "esop-administration", title: "esop administration", category: "Finance & Legal", filename: "ARG-Builder-esop-administration.md" },
  { id: "event-driven-architecture", title: "event driven architecture", category: "Engineering", filename: "ARG-Builder-event-driven-architecture.md" },
  { id: "i18n-Implementation-Guide", title: "i18n Implementation Guide", category: "Customer Success", filename: "ARG-Builder-i18n-Implementation-Guide.md" },
  { id: "monolith-to-microservices-migration", title: "monolith to microservices migration", category: "Engineering", filename: "ARG-Builder-monolith-to-microservices-migration.md" },
  { id: "product-experimentation-culture", title: "product experimentation culture", category: "Product", filename: "ARG-Builder-product-experimentation-culture.md" },
  { id: "product-growth-loops-viral-mechanics", title: "product growth loops viral mechanics", category: "Product", filename: "ARG-Builder-product-growth-loops-viral-mechanics.md" },
  { id: "real-time-data-streaming-architecture", title: "real time data streaming architecture", category: "Engineering", filename: "ARG-Builder-real-time-data-streaming-architecture.md" },
  { id: "saas-embedded-analytics-reporting", title: "saas embedded analytics reporting", category: "Data & Analytics", filename: "ARG-Builder-saas-embedded-analytics-reporting.md" },
  { id: "saas-freemium-strategy", title: "saas freemium strategy", category: "Strategy & Operations", filename: "ARG-Builder-saas-freemium-strategy.md" },
  { id: "saas-marketplace-integration-ecosystem-strategy", title: "saas marketplace integration ecosystem strategy", category: "Partnerships & GTM", filename: "ARG-Builder-saas-marketplace-integration-ecosystem-strategy.md" },
  { id: "sales-multi-channel-attribution-roi-measurement", title: "sales multi channel attribution roi measurement", category: "Sales", filename: "ARG-Builder-sales-multi-channel-attribution-roi-measurement.md" },
  { id: "sales-poc-management", title: "sales poc management", category: "Sales", filename: "ARG-Builder-sales-poc-management.md" },
  { id: "startup-board-observer-information-rights", title: "startup board observer information rights", category: "Strategy & Operations", filename: "ARG-Builder-startup-board-observer-information-rights.md" },
  { id: "trunk-based-development-feature-flags", title: "trunk based development feature flags", category: "Engineering", filename: "ARG-Builder-trunk-based-development-feature-flags.md" },
  { id: "zero-downtime-deployment", title: "zero downtime deployment", category: "Engineering", filename: "ARG-Builder-zero-downtime-deployment.md" },
];

export const totalDocuments = 515;

export const categoryCounts: Record<string, number> = {
  "Engineering": 111,
  "Strategy & Operations": 97,
  "Customer Success": 81,
  "Sales": 53,
  "Product": 39,
  "Finance & Legal": 37,
  "Marketing": 36,
  "Partnerships & GTM": 15,
  "Revenue & Pricing": 13,
  "Security & Compliance": 10,
  "Data & Analytics": 8,
  "AI & Developer": 7,
  "Operations": 4,
  "People & Culture": 4,
};
